Repository storybookjs/aem, pull requests merged in 2020-03, with the labels that each got.

#36 Clientlib loading part 1
  README.md
  app/aem/package.json
  app/aem/src/client/preview/types/types.ts
  app/aem/src/server/aem-clientlib-txt-loader.js
  app/aem/src/server/aem-component-loader.js
  app/aem/src/server/component-loader.js
  app/aem/src/server/framework-preset-aem.ts
  examples/aem-kitchen-sink/core/wcm/components/accordion/accordion.stories.js
  package.json
Labels: Feature

#41 Refactored the render file into multiple functions instead of using one large function
  app/aem/src/client/preview/render.ts
Labels: enhancement

#43 Feature/add models to preview decorator
  README.md
  app/aem/src/client/preview/decorators/decorators.ts
  app/aem/src/client/preview/render.ts
  app/aem/src/client/preview/types/types.ts
  examples/aem-core-components/.storybook/preview.js
  examples/aem-core-components/core/wcm/components/accordion/v1/accordion/accordion.stories.js
  examples/aem-core-components/core/wcm/components/list/v2/list/list.stories.js
  examples/aem-core-components/core/wcm/components/text/v2/text/text.stories.js
  examples/aem-kitchen-sink/.storybook/preview.js
  examples/aem-kitchen-sink/components/accordion/accordion.stories.js
  examples/aem-kitchen-sink/components/list/list.stories.js
  examples/aem-kitchen-sink/components/person/person.stories.js
  examples/aem-kitchen-sink/components/text/text.stories.js
  examples/aem-kitchen-sink/core/wcm/components/list/list.stories.js
Labels: Feature

#44 Fix yarn prepare
  app/aem/tsconfig.json
  scripts/compile-tsc.js
Labels: bug
